function skillsMember() {
    return {
        skills: [
            'JavaScript',
            'HTML',
            'CSS',
            'React',
            'Node.js',
            'Express.js',
            'MongoDB',
            'Git',
            'Python',
            'Django',
            'MySQL',
            'Java',
            'Spring Boot',
            'C',
            'C++',
            'C#',
            'PHP',
            'Laravel',
            'Ruby',
            'Ruby on Rails',
            'Swift',
            'Kotlin',
            'Flutter',
            'Dart',
            'Android',
            'iOS',
            'TensorFlow',
            'PyTorch',
            'Machine Learning',
            'Data Science',
            'Deep Learning',
            'Computer Vision',
            'Natural Language Processing',
            'Artificial Intelligence',
            'Blockchain',
            'Ethereum',
            'Solidity',
            'Web3.js',
            'Truffle',
            'IPFS',
            'Decentralized Finance (DeFi)',
            'Web Development',
            'Mobile Development',
            'Full Stack Development',
            'Backend Development',
            'Frontend Development',
            'UI/UX Design',
            'Responsive Design',
            'Progressive Web Apps (PWAs)',
            'Single Page Applications (SPAs)',
            'Serverless',
            'Microservices',
            'RESTful APIs',
            'GraphQL',
            'Docker',
            'Kubernetes',
            'AWS',
            'Azure',
            'Google Cloud Platform (GCP)',
            'Firebase',
            'Heroku',
            'Netlify',
            'Vercel',
            'JAMstack',
            'Next.js',
            'Gatsby',
            'Nuxt.js',
            'Vue.js',
            'Angular',
            'Svelte',
            'Tailwind CSS',
            'Bootstrap',
            'Material-UI',
            'Chakra UI',
            'Styled Components',
            'Jest',
            'Mocha',
            'Chai',
            'Cypress',
            'React Testing Library',
            'Enzyme',
            'Jasmine',
            'Karma',
            'Puppeteer',
            'Webpack',
            'Babel',
            'TypeScript',
            'Flow',
            'ESLint',
            'Prettier',
            'Husky',
            'Lint-Staged',
            'JSDoc',
            'BEM',
            'OOCSS',
        ],
    };
}